variables:
  AcrName: "campprodjpeplatacr" # Production ACR
  ResourceGroupName: "camp-prod-jpe-app-rg"
  ContainerAppName: "camp-prod-jpe-back-aca"
  ContainerAppEnvironment: "camp-prod-jpe-back-aca-env"
