parameters:
  pythonVersion: ""
  azureSubscription: ""
  AcrName: ""
  ImageRepo: ""

jobs:
  - job: BuildAndPush
    displayName: "Build, Test & Push Image"
    pool:
      vmImage: ubuntu-latest

    variables:
      ImageTag: "$(Build.BuildId)"

    steps:
      - checkout: self
        clean: true

      - task: Cache@2
        inputs:
          key: 'uv-cache | "$(Agent.OS)" | pyproject.toml | .python-version'
          path: $(HOME)/.cache/uv
        displayName: "Cache UV packages"

      - script: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "##vso[task.prependpath]$HOME/.cargo/bin"
        displayName: "Install UV"

      - script: uv python install
        displayName: "Install Python"

      - script: uv sync --frozen
        displayName: "Sync dependencies"

      - script: |
          uv run ruff check src tests
          uv run ruff format --check src tests
        displayName: "Run Ruff Lint"

      # - script: |
      #     uv run pytest
      #   displayName: "Run Tests"

      - task: AzureCLI@2
        displayName: "Build & Push Container Image (ACR Build)"
        inputs:
          azureSubscription: ${{ parameters.azureSubscription }}
          scriptType: bash
          scriptLocation: inlineScript
          inlineScript: |
            IMAGE_NAME="${{ parameters.AcrName }}.azurecr.io/${{ parameters.ImageRepo }}:$(Build.BuildId)"

            az acr build \
              --registry "${{ parameters.AcrName }}" \
              --image "${{ parameters.ImageRepo }}:$(Build.BuildId)" \
              .

            echo "##vso[task.setvariable variable=ImageName]$IMAGE_NAME"
